/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

/**
 *
 * @author ny200852
 */
public class availableSeats extends javax.swing.JFrame {

    /**
     * Creates new form availableSeats
     */
    public availableSeats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton7c = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jToggleButton2b = new javax.swing.JToggleButton();
        jToggleButton5d = new javax.swing.JToggleButton();
        jToggleButton3b = new javax.swing.JToggleButton();
        jToggleButton1b = new javax.swing.JToggleButton();
        jToggleButton3c = new javax.swing.JToggleButton();
        jToggleButton4b = new javax.swing.JToggleButton();
        jToggleButton8e = new javax.swing.JToggleButton();
        jToggleButton5e = new javax.swing.JToggleButton();
        jToggleButton1a = new javax.swing.JToggleButton();
        jToggleButton5a = new javax.swing.JToggleButton();
        jToggleButton2a = new javax.swing.JToggleButton();
        jToggleButton6e = new javax.swing.JToggleButton();
        jToggleButton1d = new javax.swing.JToggleButton();
        jToggleButton2d = new javax.swing.JToggleButton();
        jToggleButton5b = new javax.swing.JToggleButton();
        jToggleButton6a = new javax.swing.JToggleButton();
        jToggleButton6b = new javax.swing.JToggleButton();
        jToggleButton7b = new javax.swing.JToggleButton();
        jToggleButton4c = new javax.swing.JToggleButton();
        jToggleButton3a = new javax.swing.JToggleButton();
        jToggleButton5c = new javax.swing.JToggleButton();
        jToggleButton8c = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jToggleButton7a = new javax.swing.JToggleButton();
        jToggleButton6d = new javax.swing.JToggleButton();
        jToggleButton1e = new javax.swing.JToggleButton();
        jToggleButton7e = new javax.swing.JToggleButton();
        jToggleButton8a = new javax.swing.JToggleButton();
        jToggleButton3d = new javax.swing.JToggleButton();
        jToggleButton7d = new javax.swing.JToggleButton();
        jToggleButton2e = new javax.swing.JToggleButton();
        jToggleButton8d = new javax.swing.JToggleButton();
        jToggleButton3e = new javax.swing.JToggleButton();
        jToggleButton8b = new javax.swing.JToggleButton();
        jToggleButton1c = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton2c = new javax.swing.JToggleButton();
        jToggleButton6c = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton4d = new javax.swing.JToggleButton();
        jToggleButton4e = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton4a = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton7c.setText("jToggleButton7");

        jLabel3.setText("b");

        jToggleButton2b.setText("jToggleButton2");

        jToggleButton5d.setText("jToggleButton5");

        jToggleButton3b.setText("jToggleButton3");

        jToggleButton1b.setText("jToggleButton1");

        jToggleButton3c.setText("jToggleButton3");

        jToggleButton4b.setText("jToggleButton4");

        jToggleButton8e.setText("jToggleButton8");

        jToggleButton5e.setText("jToggleButton5");

        jToggleButton1a.setText("jToggleButton1");

        jToggleButton5a.setText("jToggleButton5");

        jToggleButton2a.setText("jToggleButton2");

        jToggleButton6e.setText("jToggleButton6");

        jToggleButton1d.setText("jToggleButton1");

        jToggleButton2d.setText("jToggleButton2");

        jToggleButton5b.setText("jToggleButton5");

        jToggleButton6a.setText("jToggleButton6");
        jToggleButton6a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6aActionPerformed(evt);
            }
        });

        jToggleButton6b.setText("jToggleButton6");

        jToggleButton7b.setText("jToggleButton7");

        jToggleButton4c.setText("jToggleButton4");

        jToggleButton3a.setText("jToggleButton3");

        jToggleButton5c.setText("jToggleButton5");

        jToggleButton8c.setText("jToggleButton8");

        jLabel11.setText("Select up to 6 seats");

        jToggleButton7a.setText("jToggleButton7");

        jToggleButton6d.setText("jToggleButton6");

        jToggleButton1e.setText("jToggleButton1");

        jToggleButton7e.setText("jToggleButton7");

        jToggleButton8a.setText("jToggleButton8");

        jToggleButton3d.setText("jToggleButton3");

        jToggleButton7d.setText("jToggleButton7");

        jToggleButton2e.setText("jToggleButton2");

        jToggleButton8d.setText("jToggleButton8");

        jToggleButton3e.setText("jToggleButton3");

        jToggleButton8b.setText("jToggleButton8");

        jToggleButton1c.setText("jToggleButton1");

        jLabel4.setText("c");

        jToggleButton2c.setText("jToggleButton2");

        jToggleButton6c.setText("jToggleButton6");

        jLabel1.setText("     1        2           3          4          5         6        7          8     ");

        jLabel5.setText("d");

        jToggleButton4d.setText("jToggleButton4");

        jToggleButton4e.setText("jToggleButton4");

        jLabel2.setText("a");

        jLabel6.setText("e");

        jToggleButton4a.setText("jToggleButton4");

        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Confirm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jToggleButton1b, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton2b, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton3b, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton4b, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton5b, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton6b, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton7b, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton8b, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jToggleButton1c, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton2c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton3c, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton4c, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton5c, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton6c, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton7c, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton8c, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jToggleButton1d, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton2d, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton3d, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton4d, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton5d, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton6d, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton7d, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton8d, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jToggleButton1a, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton2a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton3a, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton4a, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton5a, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton6a, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton7a, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton8a, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton4)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jToggleButton1e, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jToggleButton2e, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jToggleButton3e, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jToggleButton4e, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jToggleButton5e, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton6e, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton7e, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButton8e, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1a)
                    .addComponent(jToggleButton2a)
                    .addComponent(jToggleButton3a)
                    .addComponent(jToggleButton4a)
                    .addComponent(jToggleButton5a)
                    .addComponent(jToggleButton6a)
                    .addComponent(jToggleButton7a)
                    .addComponent(jToggleButton8a)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1b)
                    .addComponent(jToggleButton2b)
                    .addComponent(jToggleButton3b)
                    .addComponent(jToggleButton4b)
                    .addComponent(jToggleButton5b)
                    .addComponent(jToggleButton6b)
                    .addComponent(jToggleButton7b)
                    .addComponent(jToggleButton8b)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1c)
                    .addComponent(jToggleButton2c)
                    .addComponent(jToggleButton3c)
                    .addComponent(jToggleButton4c)
                    .addComponent(jToggleButton5c)
                    .addComponent(jToggleButton6c)
                    .addComponent(jToggleButton7c)
                    .addComponent(jToggleButton8c)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1d)
                    .addComponent(jToggleButton2d)
                    .addComponent(jToggleButton3d)
                    .addComponent(jToggleButton4d)
                    .addComponent(jToggleButton5d)
                    .addComponent(jToggleButton6d)
                    .addComponent(jToggleButton7d)
                    .addComponent(jToggleButton8d)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1e)
                    .addComponent(jToggleButton2e)
                    .addComponent(jToggleButton3e)
                    .addComponent(jToggleButton4e)
                    .addComponent(jToggleButton5e)
                    .addComponent(jToggleButton6e)
                    .addComponent(jToggleButton7e)
                    .addComponent(jToggleButton8e)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addComponent(jButton4)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton6aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton6aActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(availableSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(availableSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(availableSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(availableSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new availableSeats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1a;
    private javax.swing.JToggleButton jToggleButton1b;
    private javax.swing.JToggleButton jToggleButton1c;
    private javax.swing.JToggleButton jToggleButton1d;
    private javax.swing.JToggleButton jToggleButton1e;
    private javax.swing.JToggleButton jToggleButton2a;
    private javax.swing.JToggleButton jToggleButton2b;
    private javax.swing.JToggleButton jToggleButton2c;
    private javax.swing.JToggleButton jToggleButton2d;
    private javax.swing.JToggleButton jToggleButton2e;
    private javax.swing.JToggleButton jToggleButton3a;
    private javax.swing.JToggleButton jToggleButton3b;
    private javax.swing.JToggleButton jToggleButton3c;
    private javax.swing.JToggleButton jToggleButton3d;
    private javax.swing.JToggleButton jToggleButton3e;
    private javax.swing.JToggleButton jToggleButton4a;
    private javax.swing.JToggleButton jToggleButton4b;
    private javax.swing.JToggleButton jToggleButton4c;
    private javax.swing.JToggleButton jToggleButton4d;
    private javax.swing.JToggleButton jToggleButton4e;
    private javax.swing.JToggleButton jToggleButton5a;
    private javax.swing.JToggleButton jToggleButton5b;
    private javax.swing.JToggleButton jToggleButton5c;
    private javax.swing.JToggleButton jToggleButton5d;
    private javax.swing.JToggleButton jToggleButton5e;
    private javax.swing.JToggleButton jToggleButton6a;
    private javax.swing.JToggleButton jToggleButton6b;
    private javax.swing.JToggleButton jToggleButton6c;
    private javax.swing.JToggleButton jToggleButton6d;
    private javax.swing.JToggleButton jToggleButton6e;
    private javax.swing.JToggleButton jToggleButton7a;
    private javax.swing.JToggleButton jToggleButton7b;
    private javax.swing.JToggleButton jToggleButton7c;
    private javax.swing.JToggleButton jToggleButton7d;
    private javax.swing.JToggleButton jToggleButton7e;
    private javax.swing.JToggleButton jToggleButton8a;
    private javax.swing.JToggleButton jToggleButton8b;
    private javax.swing.JToggleButton jToggleButton8c;
    private javax.swing.JToggleButton jToggleButton8d;
    private javax.swing.JToggleButton jToggleButton8e;
    // End of variables declaration//GEN-END:variables
}
